"""
Django settings for TeddyTale project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import logging
from dotenv import load_dotenv
import dj_database_url
import environ

# ====================
# ИНИЦИАЛИЗАЦИЯ ПЕРЕМЕННЫХ ОКРУЖЕНИЯ
# ====================

# Загружаем переменные окружения из .env файла
load_dotenv()

# Инициализация environ для удобной работы с переменными
env = environ.Env(
    # Устанавливаем значения по умолчанию для разработки
    DEBUG=(bool, True),
    SECRET_KEY=(str, ''),
    ALLOWED_HOSTS=(list, []),
    DATABASE_URL=(str, 'sqlite:///db.sqlite3'), # Строка для SQLite
    YANDEX_MAPS_API_KEY=(str, ''),

)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ====================
# АВТОМАТИЧЕСКОЕ СОЗДАНИЕ ДИРЕКТОРИЙ
# ====================

def ensure_directories_exist():
    """
    Создает необходимые директории при запуске приложения.
    Вызывается автоматически при импорте настроек.
    """
    directories = [
        BASE_DIR / 'logs',
        BASE_DIR / 'media',
        BASE_DIR / 'static',
        ]

    # Добавляем STATIC_ROOT, если он определен
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    if STATIC_ROOT:
        directories.append(Path(STATIC_ROOT))

    for directory in directories:
        try:
            directory.mkdir(exist_ok=True, mode=0o755)
            # Проверяем права на запись
            test_file = directory / '.write_test'
            test_file.touch(exist_ok=True)
            test_file.unlink(missing_ok=True)
        except Exception as e:
            # Используем базовый логгер, так как наши настройки еще не загружены
            logging.basicConfig(level=logging.WARNING)
            logger = logging.getLogger(__name__)
            logger.warning(f"Не удалось создать директорию {directory}: {e}")
            # Не прерываем выполнение, так как приложение может работать без некоторых директорий

# Создаем необходимые директории
ensure_directories_exist()

# ====================
# БЕЗОПАСНОСТЬ
# ====================

# Читаем секретный ключ из переменной окружения или используем fallback
SECRET_KEY = env('SECRET_KEY')

DEBUG = env.bool('DEBUG', default=False)

# Разрешенные хосты
ALLOWED_HOSTS = env.list('DJANGO_ALLOWED_HOSTS')

RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# ====================
# ПРИЛОЖЕНИЯ
# ====================

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_cleanup.apps.CleanupConfig',

    'landing',
    'teddy_admin',
    'TeddyTale',
]

# ====================
# БАЗА ДАННЫХ
# ====================

# Определяем, работаем ли мы на Render
IS_RENDER = os.environ.get('RENDER') is not None

# Разделяем настройки для разработки и продакшена
if 'DATABASE_URL' in os.environ:
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=300 if IS_RENDER else 600,  # Разные настройки для Render
            conn_health_checks=True,
            ssl_require=True
        )
    }

    # Указываем движок базы данных
    DATABASES['default']['ENGINE'] = 'django.db.backends.postgresql'

    # Эти настройки помогают избежать таймаутов при "засыпании" приложения
    connection_options = {
        'connect_timeout': 15,
        'keepalives': 1,
        'keepalives_idle': 60,
        'keepalives_interval': 10,
        'keepalives_count': 5,
        'sslmode': 'require',
    }

    # Получаем DATABASE_URL для проверок
    database_url = os.environ.get('DATABASE_URL', '')

    # Если мы на Render, добавляем дополнительные оптимизации
    if IS_RENDER:
        # Специальные настройки для Render.com
        connection_options.update({
            'connect_timeout': 20,
            'keepalives_idle': 30,
            'application_name': 'teddytale_render_app',  # Идентификатор приложения для мониторинга
        })

        # Проверяем, содержит ли DATABASE_URL правильный хост для пулера соединений
        if 'pooler.supabase.com' not in database_url and 'supabase.com' in database_url:
            print("ВНИМАНИЕ: Рекомендуется использовать Supabase Connection Pooler для production.")
            print("Измените DATABASE_URL, заменив 'db.' на 'aws-0-eu-central-1.pooler.'")

    # Применяем настройки соединения
    DATABASES['default'].setdefault('OPTIONS', {}).update(connection_options)

    # Эта настройка помогает автоматически восстанавливать соединения после "засыпания"
    DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True

    # Логируем информацию о подключении (только при DEBUG)
    if DEBUG:
        print(f"База данных настроена для {'Render' if IS_RENDER else 'продакшена'}")
        print(f"CONN_MAX_AGE: {DATABASES['default'].get('CONN_MAX_AGE', 'не задан')}")
        print(f"Используется Connection Pooler: {'pooler.supabase.com' in database_url}")

else:
    # Локальная разработка с SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# ====================
# НАСТРОЙКИ БЕЗОПАСНОСТИ
# ====================

# URL для входа в стандартную админку Django
LOGIN_URL = '/enter-admin-panel/'

# Настройки безопасности
SESSION_COOKIE_NAME = 'teddy_admin_session'
CSRF_COOKIE_NAME = 'teddy_admin_csrftoken'

SESSION_COOKIE_AGE = env.int('SESSION_COOKIE_AGE', default=1209600)  # 2 недели
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Настройки CSRF
CSRF_USE_SESSIONS = True
CSRF_COOKIE_HTTPONLY = True  # Должно быть False для доступа JavaScript
# True если используем HTTPS
CSRF_COOKIE_SECURE = env.bool('CSRF_COOKIE_SECURE', default=False)
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'https://*.onrender.com',
])

if IS_RENDER:
    # Получаем домен Render из переменной окружения
    render_domain = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
    if render_domain and render_domain not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(render_domain)

    # Также добавляем общий домен для health-check мониторинга
    if '*.onrender.com' not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append('*.onrender.com')

# Дополнительные настройки безопасности для продакшена
if not DEBUG:
    SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=False)
    SECURE_HSTS_SECONDS = env.int('SECURE_HSTS_SECONDS', default=0)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool('SECURE_HSTS_INCLUDE_SUBDOMAINS',
                                              default=False)
    SECURE_HSTS_PRELOAD = env.bool('SECURE_HSTS_PRELOAD', default=False)
    SESSION_COOKIE_SECURE = env.bool('SESSION_COOKIE_SECURE', default=True)
    CSRF_COOKIE_SECURE = env.bool('CSRF_COOKIE_SECURE', default=True)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'TeddyTale.middleware.SupabaseConnectionMiddleware',
]

ROOT_URLCONF = 'TeddyTale.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',            # Глобальные шаблоны
            BASE_DIR / 'landing/templates',    # Шаблоны приложения landing
            BASE_DIR / 'teddy_admin/templates',  # Шаблоны кастомной админки
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'landing.context_processors.yandex_maps_api_key',
            ],
        },
    },
]

WSGI_APPLICATION = 'TeddyTale.wsgi.application'

# ====================
# ВАЛИДАЦИЯ ПАРОЛЕЙ
# ====================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ====================
# МЕЖДУНАРОДНЫЕ НАСТРОЙКИ
# ====================

LANGUAGE_CODE = env('LANGUAGE_CODE', default='ru-RU')

TIME_ZONE = env('TIME_ZONE', default='Europe/Moscow')

USE_I18N = True
USE_L10N = True
USE_TZ = True

# Форматы дат для русского языка
DATE_FORMAT = 'd E Y'  # 15 января 2024
DATETIME_FORMAT = 'd E Y H:i'  # 15 января 2024 14:30
SHORT_DATE_FORMAT = 'd.m.Y'  # 15.01.2024
SHORT_DATETIME_FORMAT = 'd.m.Y H:i'  # 15.01.2024 14:30

# ====================
# ОБРАБОТКА ОШИБОК
# ====================

# При DEBUG = False Django будет использовать эти шаблоны для ошибок
if not DEBUG:
    handler404 = 'landing.views.page_not_found'
    handler500 = 'landing.views.server_error'
    handler403 = 'landing.views.permission_denied'
    handler400 = 'landing.views.bad_request'
    handler503 = 'landing.views.service_unavailable_view'

# ====================
# СТАТИЧЕСКИЕ И МЕДИА ФАЙЛЫ
# ====================

STATIC_URL = '/static/'

# Где ищем статические файлы
STATICFILES_DIRS = [BASE_DIR / "static"]

# Для продакшена (когда DEBUG = False)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

WHITENOISE_MANIFEST_STRICT = False  # Игнорировать отсутствующие файлы
WHITENOISE_USE_FINDERS = True  # Искать файлы в STATICFILES_DIRS
WHITENOISE_AUTOREFRESH = True  # Автообновление в dev-режиме

# Настройки для медиафайлов (изображения)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / env('MEDIA_ROOT', default='media')

# ====================
# НАСТРОЙКИ LOGGING
# ====================

# Уровень логирования из .env
LOG_LEVEL = env('LOG_LEVEL', default='INFO')

# Настройки логирования с ротацией
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d}'
                      ' {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'detailed': {
            'format': '[{asctime}] {levelname} {name} - {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'level': LOG_LEVEL,
            'class': 'logging.StreamHandler',
            'formatter': 'detailed',
        },
        'file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
            # 1 MB по умолчанию
            'maxBytes': env.int('LOG_MAX_BYTES', default=1048576),
            # 3 резервные копии
            'backupCount': env.int('LOG_BACKUP_COUNT', default=3),
            'encoding': 'utf-8',
        },
        'landing_file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'landing.log',
            'formatter': 'detailed',
            'maxBytes': env.int('LOG_MAX_BYTES', default=1048576),
            'backupCount': env.int('LOG_BACKUP_COUNT', default=3),
            'encoding': 'utf-8',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'errors.log',
            'formatter': 'verbose',
            'maxBytes': env.int('LOG_MAX_BYTES', default=1048576),
            'backupCount': env.int('LOG_BACKUP_COUNT', default=3),
            'encoding': 'utf-8',
        },
        # Добавляем логгер для базы данных (важно для отладки подключений)
        'db_file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'database.log',
            'formatter': 'detailed',
            'maxBytes': env.int('LOG_MAX_BYTES', default=1048576),
            'backupCount': env.int('LOG_BACKUP_COUNT', default=3),
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file', 'error_file'],
            'level': LOG_LEVEL,
            'propagate': True,
        },
        'django.db.backends': {
            'handlers': ['console', 'db_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['error_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'landing': {
            'handlers': ['console', 'landing_file', 'error_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'teddy_admin': {
            'handlers': ['console', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'TeddyTale': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console', 'error_file'],
        'level': 'WARNING',
    },
}

# ====================
# ПРОЧИЕ НАСТРОЙКИ
# ====================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Jazzmin настройки
JAZZMIN_SETTINGS = {
    "site_title": "Teddy'sTale",
    "site_header": "Управление контентом",
    "welcome_sign": "Добро пожаловать!",
    "site_logo": "assets/icon/main_logo.svg",
    "site_logo_classes": "navbar-logo",
    "site_icon": "assets/icon/favicon.svg",

    # Меню
    "topmenu_links": [
        {"name": "Сайт", "url": "/", "new_window": True},
    ],

    # Боковое меню
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": [
        "main.PageSection",
        "main.SectionContent",
        "main.ShopItem",
        "main.UploadedImage",
        "main.SiteSettings",
        "main.ChangeLog",
    ],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.group": "fas fa-users",
        "main.PageSection": "fas fa-th-large",
        "main.SectionContent": "fas fa-edit",
        "main.ShopItem": "fas fa-shopping-bag",
        "main.SiteSettings": "fas fa-cog",
        "main.ChangeLog": "fas fa-history",
        "main.UploadedImage": "fas fa-image",
    },

    # Внешний вид
    "show_sidebar": True,
    "use_custom_cdn": False,
    "show_ui_builder": False,
    "changeform_format": "vertical_tabs",
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-light",
    "accent": "accent-pink",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "sidebar": "sidebar-dark-pink",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": True,
    "sidebar_collapse": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-pink",
        "secondary": "btn-outline-secondary",
    }
}

# ====================
# API КЛЮЧИ
# ====================

# Ключ Яндекс.Карт
YANDEX_MAPS_API_KEY = env('YANDEX_MAPS_API_KEY', default='')

# ====================
# НОВЫЕ НАСТРОЙКИ ДЛЯ RENDER И SUPABASE
# ====================

# ИСПРАВЛЕНИЕ 11: Константа для проверки окружения Render
RENDER = IS_RENDER

# Настройки для health-check эндпоинтов (важно для мониторинга)
# Эти настройки помогут UptimeRobot отслеживать доступность приложения
HEALTH_CHECK = {
    'ENABLED': True,
    'PATH': '/health/',
    'PING_PATH': '/ping/',
    'TIMEOUT': 30,  # Секунды для health-check таймаута
}

# Информация для разработчика
if DEBUG and IS_RENDER:
    print("\n" + "="*80)
    print("ВАЖНО ДЛЯ НАСТРОЙКИ RENDER + SUPABASE:")
    print("="*80)
    print("1. Убедитесь, что в переменных окружения Render заданы:")
    print("   - DATABASE_URL (с использованием Connection Pooler)")
    print("   - RENDER_EXTERNAL_HOSTNAME (автоматически)")
    print("2. Используйте Supabase Connection Pooler URL:")
    print("   Пример: postgresql://postgres.[id]:[password]@aws-0-eu-central-1.pooler.supabase.com:5432/postgres")
    print("3. Настройте UptimeRobot для мониторинга health-эндпоинтов:")
    print("   - Основной: https://ваш-проект.onrender.com/health")
    print("   - Резервный: https://ваш-проект.onrender.com/ping")
    print("4. Добавьте в requirements.txt для надежности:")
    print("   - requests>=2.31.0")
    print("="*80 + "\n")

# Эта функция будет вызвана в wsgi.py для инициализации менеджера соединений
def initialize_render_specific_settings():
    """
    Инициализирует специфичные для Render настройки.
    Вызывается в wsgi.py и asgi.py при запуске приложения.
    """
    if IS_RENDER:
        # Логируем информацию о конфигурации базы данных
        logger = logging.getLogger(__name__)
        logger.info(f"Приложение запущено на Render")
        logger.info(f"CONN_MAX_AGE настроен на {DATABASES['default'].get('CONN_MAX_AGE', 'не задан')} секунд")
        logger.info(f"Таймаут подключения: {DATABASES['default'].get('OPTIONS', {}).get('connect_timeout', 'не задан')} секунд")

# ====================
# РАБОТА С МЕДИА-ФАЙЛАМИ НА RENDER
# ====================

if IS_RENDER:
    # Убедимся, что медиа-директории созданы
    import os
    from pathlib import Path

    # Создаем поддиректории внутри media
    media_subdirs = ['shop_items', 'uploaded_images', 'tmp']
    for subdir in media_subdirs:
        dir_path = Path(MEDIA_ROOT) / subdir
        dir_path.mkdir(parents=True, exist_ok=True)

    # Логируем информацию о медиа-конфигурации
    import logging
    logger = logging.getLogger(__name__)
    logger.info(f"Render mode: MEDIA_ROOT={MEDIA_ROOT}")

    # Настройки WhiteNoise для работы с медиа-файлами
    WHITENOISE_USE_FINDERS = True
    WHITENOISE_MANIFEST_STRICT = False
    WHITENOISE_ALLOW_ALL_ORIGINS = True

    # Увеличиваем максимальный размер файла для WhiteNoise (по умолчанию 1MB)
    WHITENOISE_MAX_AGE = 31536000  # 1 год кэширования для статических файлов